from google.cloud import bigquery

VENUE_PERFORMANCE_SCHEMA = [
    bigquery.SchemaField("datasource", "STRING"),
    bigquery.SchemaField("no", "INTEGER"),
    bigquery.SchemaField("event_month", "STRING"),
    bigquery.SchemaField("regional_office_name", "STRING"),
    bigquery.SchemaField("branch_name", "STRING"),
    bigquery.SchemaField("facility_name", "STRING"),
    bigquery.SchemaField("floor_label", "STRING"),
    bigquery.SchemaField("floor_number", "INTEGER"),
    bigquery.SchemaField("floor_number_above_ground", "INTEGER"),
    bigquery.SchemaField("is_basement_floor", "BOOLEAN"),
    bigquery.SchemaField("floor_category", "STRING"),
    bigquery.SchemaField("space_name", "STRING"),
    bigquery.SchemaField("area_raw", "STRING"),
    bigquery.SchemaField("area_sqm", "INTEGER"),
    bigquery.SchemaField("area_group", "STRING"),
    bigquery.SchemaField("is_area_unconfirmed", "BOOLEAN"),
    bigquery.SchemaField("is_daily_venue", "BOOLEAN"),
    bigquery.SchemaField("helper_company_name", "STRING"),
    bigquery.SchemaField("staff_count", "STRING"),
    bigquery.SchemaField("staff_count_numeric", "INTEGER"),
    bigquery.SchemaField("start_date", "DATE"),
    bigquery.SchemaField("end_date", "DATE"),
    bigquery.SchemaField("actual_days_raw", "STRING"),
    bigquery.SchemaField("actual_days", "INTEGER"),
    bigquery.SchemaField("date", "DATE"),
    bigquery.SchemaField("daily_result_raw", "STRING"),
    bigquery.SchemaField("daily_result", "INTEGER"),
    bigquery.SchemaField("is_missing_input", "BOOLEAN"),
    bigquery.SchemaField("is_event_cancelled", "BOOLEAN"),
]
